name: banking

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-banking-app
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql-banking-data:/var/opt/mssql
    restart: always


volumes:
  mssql-banking-data: